#!/usr/bin/env bash
# Curated Enterprise GA fault-injection suite (listener / upstream / controller /
# disk / network). Run from the Gateway crate root.
#
# Always builds with `kube,redis,wire` so network-class Redis fail-closed cases
# and optional wire fail_closed escalation blocks are part of the default
# promotion gate (no opt-in env). Redis tests target an unreachable URL
# (`127.0.0.1:1`); a live Redis server is not required.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

FILTERS=(
  response_middleware_error_fails_closed_instead_of_returning_upstream_body
  response_middleware_error_fails_closed_on_sse_listener_without_upstream_body
  response_middleware_error_fails_closed_on_grpc_listener_without_upstream_stream
  response_middleware_error_fails_closed_on_distributed_json_listener_without_power_body
  response_middleware_error_fails_closed_on_distributed_sse_listener_without_power_body
  response_middleware_error_fails_closed_on_native_models_listener_without_policy_body
  response_middleware_error_fails_closed_on_proxy_failure
  forward_auth_unreachable_returns_502_on_listener_without_upstream_contact
  forward_auth_deny_returns_auth_status_on_listener_without_upstream_contact
  acme_http01_challenge_is_served_from_runtime_store_before_routes
  acme_certificate_install_hot_swaps_live_https_acceptor
  passive_health_half_open_recovery_readmits_traffic_after_recovery_time
  passive_health_half_open_still_broken_reblacklists_after_threshold
  circuit_breaker_half_open_probe_closes_after_success_on_listener
  circuit_breaker_half_open_still_failing_reopens_on_listener
  failover_routes_to_backup_on_listener_when_primary_unhealthy
  active_health_check_evicts_backend_on_listener_then_readmits_when_healthy
  active_health_check_evicts_revision_only_backend_on_listener_then_readmits_when_healthy
  active_health_redirect_does_not_follow_or_mark_healthy
  sticky_session_cookie_pins_backend_on_listener
  sticky_session_cookie_pins_websocket_backend_on_listener
  traffic_mirror_copies_buffered_request_to_shadow_on_listener
  traffic_mirror_primary_still_succeeds_when_shadow_unreachable_on_listener
  validate_activation_fails_closed_when_docker_daemon_unreachable
  validate_activation_fails_closed_when_kubernetes_kubeconfig_unusable
  validate_activation_fails_closed_when_kubernetes_client_cannot_build
  validate_activation_fails_closed_when_kubernetes_ingress_list_unreachable
  validate_activation_fails_closed_when_k8s_autoscaler_kubeconfig_unusable
  validate_activation_fails_closed_when_k8s_scale_subresource_unreachable
  validate_activation_fails_closed_when_box_scale_unreachable
  validate_activation_fails_closed_on_unusable_service_tls_ca_for_grpc
  validate_activation_fails_closed_on_invalid_health_check_interval
  validate_activation_fails_closed_on_unusable_health_check_tls_ca
  validate_activation_fails_closed_when_forward_auth_unreachable
  validate_activation_fails_closed_when_redis_rate_limit_unreachable
  probe_activation_rejects_unreachable_auth_service
  probe_activation_accepts_reachable_auth_service
  load_merged_gateway_config_probes_file_watch_when_enabled
  probe_file_watch_activation_accepts_existing_paths
  validate_activation_prepares_revision_health_checkers
  validate_activation_probes_box_scale_http_client
  validate_activation_probes_default_upstream_tls_clients
  validate_activation_probes_file_watch_notify_when_enabled
  validate_activation_at_path_attaches_config_parent_watch
  validate_activation_accepts_usable_acme_account_key
  validate_activation_accepts_usable_acme_stored_cert_pem
  test_validate_activation_builds_discovery_http_client
  test_validate_activation_builds_acme_manager_when_configured
  validate_activation_probes_health_check_http_clients
  validate_activation_probes_k8s_scale_subresource
  validate_activation_probes_kubernetes_ingress_list
  validate_activation_probes_reachable_docker_daemon
  validate_activation_probes_reachable_forward_auth
  validate_activation_probes_service_tls_ca_grpc_clients
  validate_activation_probes_service_tls_ca_http_clients
  validate_activation_skips_redis_probe_when_fail_open
  probe_activation_rejects_unreachable_redis
  rate_limit_redis_unreachable_returns_503_on_listener_without_upstream_contact
  rate_limit_redis_fail_open_reaches_upstream_on_listener_when_redis_unreachable
  validate_activation_fails_closed_when_acme_storage_path_is_a_file
  validate_activation_fails_closed_when_acme_storage_path_is_relative
  validate_activation_fails_closed_when_acme_account_key_corrupt
  validate_activation_fails_closed_when_acme_stored_cert_pem_corrupt
  activate_stored_certificate_fails_closed_when_sink_rejects_unusable_pem
  validate_activation_fails_closed_when_file_watch_directory_missing
  load_merged_gateway_config_fails_closed_when_directory_missing
  gateway_new_at_path_fails_closed_when_config_parent_missing
  load_merged_gateway_config_fails_closed_on_missing_entrypoint_tls_pem
  load_merged_gateway_config_fails_closed_when_management_token_env_unset
  with_middlewares_fails_closed_on_dual_retry_with_custom_policy
  validate_activation_rejects_cloud_managed_bootstrap_with_inline_traffic
  validate_activation_rejects_reserved_managed_service_middleware_name
  validate_activation_rejects_reserved_managed_service_name_prefix
  load_config_fails_closed_when_configured_directory_is_missing
  watch_fails_closed_when_configured_directory_is_missing
  generate_config_fails_closed_on_missing_port_label
  generate_config_fails_closed_on_invalid_port_label
  generate_config_fails_closed_on_missing_or_invalid_ip
  generate_config_fails_closed_on_invalid_weight_label
  generate_config_fails_closed_on_invalid_strategy_label
  generate_config_fails_closed_on_invalid_priority_label
  generate_config_fails_closed_on_tcp_protocol_without_listen_address
  generate_config_fails_closed_on_udp_protocol_without_listen_address
  generate_config_fails_closed_on_unknown_protocol_label
  ingress_to_config_fails_closed_on_invalid_strategy_annotation
  ingress_to_config_fails_closed_on_invalid_priority_annotation
  ingress_to_config_fails_closed_on_empty_request_timeout_annotation
  ingress_to_config_fails_closed_on_invalid_request_timeout_annotation
  ingress_to_config_fails_closed_on_zero_backend_port
  ingress_to_config_fails_closed_on_named_backend_port_without_number
  ingress_to_config_fails_closed_on_tcp_without_listen
  ingress_to_config_fails_closed_on_udp_without_listen
  ingress_to_config_fails_closed_on_unknown_protocol_annotation
  ingress_routes_to_config_fails_closed_on_invalid_backend_strategy
  build_sticky_managers_fails_closed_on_invalid_cookie_name
  build_mirror_failover_fails_closed_when_mirror_target_missing_from_registry
  build_mirror_failover_fails_closed_when_failover_target_missing_from_registry
  scheduled_models_fail_closed_when_worker_observations_are_absent
  scheduled_models_fail_closed_when_service_has_no_configured_workers
  scheduled_models_fail_closed_without_exact_managed_endpoint_ownership
  expired_worker_observations_fail_closed_without_upstream_contact
  validate_activation_fails_closed_when_usage_spool_has_untracked_file
  validate_activation_fails_closed_when_usage_spool_locked
  validate_activation_fails_closed_when_usage_spool_parent_unusable
  probe_activation_fails_closed_when_exclusive_lock_is_held
  probe_activation_fails_closed_when_spool_parent_is_not_a_directory
  validate_activation_fails_closed_when_usage_spool_epoch_record_corrupt
  probe_activation_fails_closed_when_ready_epoch_record_is_corrupt
  validate_activation_fails_closed_when_usage_spool_prepared_epoch_corrupt
  probe_activation_fails_closed_when_prepared_epoch_record_is_corrupt
  probe_activation_fails_closed_when_compacting_epoch_final_is_a_directory
  validate_activation_fails_closed_when_usage_spool_recovery_artifact_is_a_directory
  probe_activation_fails_closed_when_recovery_artifact_is_a_directory
  probe_activation_rejects_retained_bytes_over_capacity_like_open
  probe_activation_rejects_missing_boot_epoch_headroom_like_open
  probe_activation_rejects_untracked_paths_like_open
  probe_activation_accepts_deleted_retiring_epoch_like_open
  probe_activation_write_probe_leaves_no_untracked_artifact
  probe_activation_projects_empty_epoch_reclaim_before_capacity_like_open
  probe_activation_projects_partial_ack_compaction_before_capacity_like_open
  validate_activation_fails_closed_when_usage_cloud_ingest_bearer_env_unset
  validate_activation_fails_closed_when_usage_cloud_ingest_mtls_identity_missing
  validate_activation_fails_closed_on_corrupt_managed_snapshot_journal
  validate_activation_fails_closed_when_managed_snapshot_journal_parent_unusable
  validate_activation_fails_closed_when_static_bundle_object_digest_mismatches
  gateway_new_fails_closed_on_a_usage_spool_identity_mismatch
  with_managed_service_state_fails_construct_when_owner_lock_held
  corrupt_managed_service_state_fails_gateway_construct_closed
  validate_activation_fails_closed_when_distributed_serving_api_key_env_unset
  validate_activation_fails_closed_when_distributed_serving_api_key_invalid
  reload_disabling_acme_aborts_manager
  reload_rejects_standalone_to_cloud_managed_transition
  probe_box_scale_activation_rejects_unreachable_executor
  probe_file_watch_activation_rejects_missing_directory
  ready_binding_missing_entrypoint_fails_gateway_construct_closed
  ready_binding_max_priority_base_router_fails_gateway_construct_closed
  retiring_state_without_the_exact_drain_key_fails_construct_closed
  standalone_missing_digest_object_in_local_store_fails_validate
  standalone_missing_local_digest_store_directory_fails_validate
  standalone_static_bundle_without_local_digest_store_fails_validate
  cloud_managed_static_bundles_without_object_authority_fail_validate
  test_validate_udp_zero_timeout_fails_closed
  test_validate_acme_without_email_fails_closed
  test_validate_acme_without_domains_fails_closed
  udp_zero_session_timeout_fails_listener_policy
  udp_zero_max_sessions_fails_listener_policy
  tcp_invalid_allowed_ip_fails_listener_policy
  acme_without_email_fails_listener_policy
  managed_snapshot_expiry_rejects_new_requests_on_the_listener_with_503
  managed_snapshot_expiry_rejects_new_tcp_connections_without_upstream
  managed_snapshot_expiry_rejects_new_udp_datagrams_without_upstream
  credential_successor_runtime_revokes_prior_key_without_upstream
  grant_successor_runtime_denies_prior_model_without_upstream
  managed_snapshot_apply_grant_successor_denies_withdrawn_model_without_upstream
  managed_snapshot_apply_credential_successor_revokes_prior_key_without_upstream
  managed_snapshot_apply_credential_generation_bump_invalidates_prior_bearer_without_upstream
  managed_inference_fails_closed_before_dispatch_when_usage_capacity_is_full
  managed_inference_policy_expiry_fails_closed_at_request_time
  managed_inference_revoked_or_expired_credentials_fail_closed_without_upstream
  node_api_client_ca_refuses_partial_trust_anchor_load
  test_management_config_rejects_client_ca_without_require_client_cert
  test_management_config_rejects_empty_allowed_ips
  test_management_config_rejects_empty_auth_token_env
  test_validate_rejects_health_check_without_probeable_servers
  test_validate_rejects_health_check_with_non_http_revision_servers
  test_validate_rejects_tls_ca_file_without_https_servers
  test_validate_rejects_invalid_sticky_cookie_name
  test_validate_discovery_rejects_empty_seeds
  test_validate_discovery_rejects_duplicate_seeds
  discovery_provider_new_requires_buildable_http_client
  test_load_config_rejects_non_acl_main_extension
  health_checker_probe_rejects_unusable_pem
  grpc_proxy_try_with_ca_file_rejects_unusable_pem
  spa_fallback_never_masks_missing_assets_or_posts
  spa_fallback_eligibility_rejects_api_namespace
  head_verifies_via_port_head_without_authority_get
  static_bundle_listener_preserves_sealed_bytes_under_compress
  static_bundle_listener_drains_inflight_get_across_runtime_replace
  sealed_content_encoding_is_emitted_without_accept_encoding_negotiation
  fail_closed_blocks_escalation_in_upstream_response
  blocks_escalation_on_response_when_fail_closed
)

case "$(uname -s 2>/dev/null || echo unknown)" in
  Linux|Darwin)
    FILTERS+=(
      spool_storage_is_private_and_insecure_permissions_fail_closed
      validate_activation_fails_closed_when_usage_spool_directory_is_not_writable
      probe_activation_fails_closed_when_usage_spool_directory_is_not_writable
      linked_managed_service_state_fails_gateway_construct_closed
      broadly_readable_managed_service_state_fails_gateway_construct_closed
      validate_rejects_docker_unix_socket_host_when_path_missing
    )
    ;;
  *)
    FILTERS+=(
      default_docker_block_fails_validate_on_windows
      validate_rejects_docker_unix_socket_host_on_non_unix
    )
    ;;
esac

FEATURE_CSV="kube,redis,wire"

echo "fault-injection: running curated suite (${#FILTERS[@]} cases; features=$FEATURE_CSV)"
failed=0
for filter in "${FILTERS[@]}"; do
  echo "fault-injection: case $filter"
  output="$(mktemp)"
  set +e
  cargo test --lib --features "$FEATURE_CSV" "$filter" -- --nocapture >"$output" 2>&1
  status=$?
  set -e
  cat "$output"
  if (( status != 0 )); then
    echo "fault-injection: FAIL $filter (cargo exit $status)" >&2
    failed=1
  elif grep -q 'running 0 tests' "$output"; then
    echo "fault-injection: FAIL $filter (no tests matched filter)" >&2
    failed=1
  fi
  rm -f "$output"
done

if (( failed != 0 )); then
  echo "fault-injection: suite failed" >&2
  exit 1
fi
echo "fault-injection: OK"
